version: '3.8'

services:

  backend:
    build: ./services/backend

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=brandenburg_db
      - POSTGRES_DB=brandenburg
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - brandenburg_db

  frontend:
    build: 
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:80
  
  pg_tileserv:
    image: pramsey/pg_tileserv:latest

    container_name: pg_tileserv

    env_file:
      - pg_tileserv.env

    depends_on:
      - brandenburg_db

    ports:
      - 7800:7800
  
  brandenburg_db:
    image: postgis/postgis
    container_name: brandenburg_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=brandenburg_db
      - POSTGRES_DB=brandenburg
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    volumes:
      - ./data:/work
      - brandenburg_db:/var/lib/postgresql/data
    ports:
      - 5433:5432

  geoserver:
    image: kartoza/geoserver:latest
    ports:
      - "8081:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    environment:
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    depends_on:
      - brandenburg_db
    
  masterportal:
    image: nginx:alpine
    container_name: masterportal
    volumes:
      - ./services/masterportal:/usr/share/nginx/html:ro
    ports:
      - 8082:80

volumes:
  brandenburg_db:
  geoserver_data: