version: '3.8'

services:

  backend:
    build: ./services/backend
    container_name: backend
    networks: 
      - my_network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=geoxai_db
      - POSTGRES_DB=geoxai
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5000:5000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./services/backend:/app
      - forest_fire_data:/app/data/forest_fire_predictor
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000 --root-path /api
    
    depends_on:
      - geoxai_db

  frontend:
    build: 
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks: 
      - my_network
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:80
    restart: unless-stopped
  
  tileserv:
    image: pramsey/pg_tileserv:20231005
    #image: pramsey/pg_tileserv:latest
    env_file:
      - pg_tileserv.env

    depends_on:
      - geoxai_db
    restart: unless-stopped
    ports:
      - "7800:7800"

    container_name: tileserv
    networks: 
      - my_network
  
  geoxai_db:
    image: postgis/postgis
    container_name: geoxai_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=geoxai_db
      - POSTGRES_DB=geoxai
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    volumes:
      - ./data:/work
      - geoxai_db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks: 
      - my_network
    restart: unless-stopped

  geoserver:
    image: kartoza/geoserver:latest
    ports:
      - "8081:8080"
    networks: 
      - my_network
    container_name: geoserver
    restart: unless-stopped
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    environment:
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_PASSWORD}
    env_file:
      - .env
    depends_on:
      - geoxai_db
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks: 
      - my_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
      - tileserv


volumes:
  geoxai_db:
  geoserver_data:
  forest_fire_data:
networks:
  my_network: