name: Build a Docker and push it to inNoWest 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
        
    steps:

      - uses: actions/checkout@v3

      - name: Listing containers
        run: docker compose ps
      
      - name: Stop running containers
        run: docker compose down

      - name: Create container data directory
        run: mkdir -p /opt/container-data

      - name: (Re)build containers
        run: docker compose build
      
      - name: Start newly built containers in detached mode
        run: docker compose up --detach